unit mipmap;


{***************************************************************}
{ |\  /|                                               We Put   }
{ | >< Hypercosm               mipmap                  3d       }
{ |/  \|                                               To Work! }
{***************************************************************}
{                                                               }
{       This module contains routines to create, prefilter      }
{       and access images using the 'mip mapping' technique.    }
{                                                               }
{***************************************************************}
{                 Copyright 1999 Hypercosm Inc.                 }
{***************************************************************}


interface


implementation


end.
